import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Menu from '@/components/menu/menu';
import Footer from '@/components/footer/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Coffee Tổ Kiến',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-x-hidden h-full min-h-svh`}
      >
        <Menu></Menu>
        {children}
        <div className="absolute top-full">
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
