import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Menu from '@/components/menu/menu';
import Footer from '@/components/footer/Footer';
//import AntsFollowingMouse from '@/components/animation/AntsFollowingMouse';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Coffee Tổ Kiến',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full  overflow-x-hidden`}
      >
        {/*<div className="absolute inset-0 z-50 pointer-events-none max-lg:hidden">
          <AntsFollowingMouse />
        </div>*/}

        <Menu />

        <div className="relative">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
